/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated automatically from configure.in by autoheader 2.13.  */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if you don't have vprintf but do have _doprnt.  */
/* #undef HAVE_DOPRNT */

/* Define if you have the strftime function.  */
#define HAVE_STRFTIME 1

/* Define if you have the vprintf function.  */
#define HAVE_VPRINTF 1

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if your <sys/time.h> declares struct tm.  */
/* #undef TM_IN_SYS_TIME */

/* Define if you have the gettimeofday function.  */
#define HAVE_GETTIMEOFDAY 1

/* Define if you have the select function.  */
#define HAVE_SELECT 1

/* Define if you have the socket function.  */
#define HAVE_SOCKET 1

/* Define if you have the strcspn function.  */
#define HAVE_STRCSPN 1

/* Define if you have the strdup function.  */
#define HAVE_STRDUP 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the strspn function.  */
#define HAVE_STRSPN 1

/* Define if you have the strtol function.  */
#define HAVE_STRTOL 1

/* Define if you have the <limits.h> header file.  */
#define HAVE_LIMITS_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the m library (-lm).  */
#define HAVE_LIBM 1

/* Define if you have the z library (-lz).  */
#define HAVE_LIBZ 1

/* Name of package */
#define PACKAGE "thales"

/* Version number of package */
#define VERSION "1.0"

/* 'table prefix to use' */
/* #undef TBL_PREFIX */

/* 'use internal hashlist' */
#define HASHLISTSUPPORT 1

/* 'ircd type' */
/* #undef IRCD_BAHAMUT */

/* 'ircd type' */
/* #undef IRCD_HYBRID */

/* 'ircd type' */
/* #undef IRCD_IRCDRU */

/* 'ircd type' */
#define IRCD_UNREAL 1

/* 'ircd type' */
/* #undef IRCD_ULTI28 */

/* 'ircd type' */
/* #undef IRCD_ULTIMATE */

/* 'ircd type' */
#define IRCD_UNREAL 1

/* 'ircd type' */
/* #undef IRCD_BAHAMUT */

/* 'ircd type' */
/* #undef IRCD_HYBRID */

/* 'ircd type' */
/* #undef IRCD_IRCDRU */

/* 'ircd type' */
/* #undef IRCD_ULTI28 */

/* 'ircd type' */
/* #undef IRCD_ULTIMATE */

/* 'dont store modes in the database ?' */
/* #undef NOMODES */

